In [217]:
import numpy as np
from sklearn.datasets import make_regression
import sklearn

In [364]:
#implementing linear regression
#numeric algorithm
class LinearRegression():
    def __init__(self,alpha = 0.01,iters = 100):
        self.alpha = alpha
        self.iters = iters
        self.errors = []
        self.weights = None
        self.N = None

    def J(self,y_pred,y_true):
        return 1/(2*self.N)*((y_pred-y_true)**2).sum()
        
    def grad_J(self,X,y_pred,y_true):
        return 1/self.N*X.T@(y_pred-y_true)

    def fit(self,X,y):
        ones = np.ones((X.shape[0],1))
        X = np.hstack((ones,X))
        self.N = X.shape[0]
        #initialize weights 
        self.weights = np.random.default_rng().standard_normal((X.shape[1],1))
        #updating weights for a given number of iterations
        for _ in range(self.iters):
            y_pred = X@self.weights
            error = self.J(y_pred,y)
            self.errors.append(error)
            gradient = self.grad_J(X,y_pred,y)
            self.weights -= gradient*self.alpha
        if self.errors[-1] > self.errors[0]:
            raise Exception('The algorithm is not diverging')

In [378]:
X,y = make_regression(
    n_samples = 100,
    n_features = 2,
    noise = 10,
    random_state = 42
)

In [379]:
X.shape

(100, 2)

In [380]:
y = y.reshape((100,1))

In [381]:
y.shape

(100, 1)

In [382]:
#My model
the_reg = LinearRegression(iters = 2000)
the_reg.fit(X,y)
the_reg.weights

array([[ 0.21633426],
       [86.0025187 ],
       [74.11676148]])

In [383]:
#sklearn model
lin_model = sklearn.linear_model.LinearRegression().fit(X,y)
lin_model

LinearRegression()

In [384]:
lin_model.intercept_

array([0.21635808])

In [385]:
lin_model.coef_

array([[86.00258028, 74.11675411]])

In [388]:
#the results are the same 
#when to stop iterations, so that is is not a hyperparameter?