In [1]:
import numpy as np
from ML_models import DecisionTreeClassifier

In [8]:
y_vec = np.array([3,3,3,5]).reshape(-1,1)
print(y_vec.shape)
y_vec 

(4, 1)


array([[3],
       [3],
       [3],
       [5]])

In [15]:
np.unique(y_vec)

array([3, 5])

In [14]:
np.unique(y_vec,return_counts = True)

(array([3, 5]), array([3, 1]))

In [2]:
dec_tree = DecisionTreeClassifier()

In [11]:
res_tup = dec_tree.calc_gini(y_vec)
res_tup

(4, array([3, 1]), np.float64(0.375))

In [13]:
res_tup[-1].item()

0.375